import {relayBar,terminalPanel,logoSvg} from './dashboard-terminal-view.js';
import type {DashboardState,DashboardRecord} from './dashboard-state.js';
import {display} from './work.js';

const esc=(v:unknown)=>String(v??'—').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const value=(v:unknown)=>typeof v==='string'||typeof v==='number'?String(v):'unknown';
const quote=(s:string)=>/^[a-zA-Z0-9_./:-]+$/.test(s)?s:`'${s.replace(/'/g,"'\\''")}'`;
const cmd=(...args:string[])=>['agenthub',...args].map(quote).join(' ');
const tone=(value:unknown)=>{const text=String(value??'unknown').toLowerCase();if(['success','found','clean','yes','done','0'].includes(text))return'positive';if(['failure','failed','error','missing','dirty','blocked'].some(word=>text.includes(word)))return'negative';if(['running','in_progress','todo','unfinished'].includes(text))return'active';return'neutral';};
const badge=(s:unknown)=>`<span class="badge badge--${tone(s)}"><i></i>${esc(s)}</span>`;
const agentBadge=(a:unknown)=>`<span class="badge badge--agent badge--${esc(a)}"><i></i>${esc(display(String(a??'')))||'—'}</span>`;
const copy=(command:string)=>`<div class="command"><code>${esc(command)}</code><button class="copy-button" type="button" data-copy="${esc(command)}" aria-label="Copy ${esc(command)}"><span aria-hidden="true">⧉</span> Copy</button></div>`;
const links=(r:DashboardRecord)=>r.links.map(l=>`<a class="artifact-link" href="/artifact/${l.id}" target="_blank" rel="noopener">${esc(l.label)}</a>`).join('');
const empty=(title:string,detail:string)=>`<div class="empty"><strong>${esc(title)}</strong><small>${esc(detail)}</small></div>`;
const table=(headers:string[],rows:string[][],emptyTitle='Nothing recorded yet')=>rows.length?`<div class="table-wrap"><table><thead><tr>${headers.map(h=>`<th scope="col">${h}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(c=>`<td>${c}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`:empty(emptyTitle,'This fills in as AgentHub records activity.');
const ago=(v:string)=>{const ms=Date.now()-Date.parse(v);if(!Number.isFinite(ms))return v;const m=Math.round(ms/60000);return m<1?'just now':m<60?`${m} min ago`:m<2880?`${Math.round(m/60)} h ago`:`${Math.round(m/1440)} d ago`;};

export function dashboardHtml(s:DashboardState,nonce:string,token='',latest?:{command:string;status:string;output:string;folder:string}) {
    const form=(action:string,label:string,fields:Record<string,string>={})=>{if(!token)return'';const kind=['run','continue','switch'].includes(action)?'costly':action==='complete'?'danger':'secondary';return `<form class="action-form" method="post" action="/actions/prepare"><input type="hidden" name="token" value="${esc(token)}"><input type="hidden" name="kind" value="${action}">${Object.entries(fields).map(([k,v])=>`<input type="hidden" name="${k}" value="${esc(v)}">`).join('')}<button class="button button--${kind}" type="submit">${kind==='costly'?'<span aria-hidden="true">◆</span> ':''}${esc(label)}</button></form>`;};
    const taskActions=(id:string,assigned?:string|null)=>`<div class="action-cluster">${form('complete','Complete + Unlock',{task:id})}${s.available.map(a=>form('run',`Run with ${a.agent}`,{task:id,agent:a.agent})+form('continue',`Continue with ${a.agent}`,{task:id,agent:a.agent})).join('')}${assigned?s.available.filter(a=>a.agent!==assigned).map(a=>form('switch',`Switch ${assigned} → ${a.agent}`,{task:id,from:assigned,to:a.agent})).join(''):''}</div>`;
    const actions:string[]=[];
    for(const task of s.tasks){if(task.status==='todo'&&task.assignedAgent)actions.push(copy(cmd('run',task.id,'--agent',task.assignedAgent,'--worktree','auto','--review')));if(task.status==='done'&&Object.values(s.locks).some(l=>l.taskId===task.id))actions.push(copy(cmd('complete',task.id,'--unlock')));if(task.status!=='done'&&task.assignedAgent){const source=s.trees.find(w=>w.agent===task.assignedAgent);if(source&&'git'in source&&source.git?.changes.some(c=>c.status!=='??'))for(const target of s.trees)if(target.agent!==source.agent&&'git'in target&&target.git?.repository&&target.git.changes.length===0)actions.push(copy(cmd('switch',task.id,'--from',source.agent,'--to',target.agent,'--apply','--continue','--review')));}}
    const drawer=(id:string,title:string,count:string,body:string,open=false)=>`<details id="${id}" class="drawer"${open?' open':''}><summary><span>${esc(title)}</span><small>${esc(count)}</small></summary><div class="drawer-body">${body}</div></details>`;
    const sessionRows=s.sessions.map(r=>[agentBadge(r.data.agent),esc(value(r.data.taskId)),badge(r.data.mode),badge(r.data.classification??(r.data.endedAt?`exit ${value(r.data.exitCode)}`:'unfinished')),`<time>${esc(value(r.data.startedAt))}</time><small>${esc(value(r.data.endedAt))}</small>`,`<div class="artifact-list">${links(r)}</div>`]);
    const switchRows=s.switches.map(r=>[esc(value(r.data.taskId)),`<span aria-label="${esc(value(r.data.from))} → ${esc(value(r.data.to))}">${agentBadge(r.data.from)}<span class="arrow">→</span>${agentBadge(r.data.to)}</span>`,badge(r.data.applied===true?'yes':'no'),badge(typeof r.data.continued==='boolean'?(r.data.continued?'yes':'no'):'not recorded'),`<time>${esc(r.time)}</time><div class="artifact-list">${links(r)}</div>`,copy(cmd('continue',value(r.data.taskId),'--agent',value(r.data.to),'--worktree','existing','--review'))]);
    const gitLabel=s.git.repository?`${s.git.changes.length} changed files`:'No Git repository';
    const recent=s.sessions.slice(0,6).map(r=>`<li>${agentBadge(r.data.agent)}<span class="recent-text"><strong>${esc(value(r.data.mode))}</strong>${r.data.taskId?` · ${esc(value(r.data.taskId))}`:''}</span><span class="recent-when">${esc(ago(r.time))}</span></li>`).join('');
    const journal=s.work.journalTail.trim();
    return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="color-scheme" content="dark">${latest?.status==='running'?'<meta http-equiv="refresh" content="3;url=/#dashboard-actions">':''}<title>AgentHub · ${esc(s.config.projectName)}</title><link rel="stylesheet" href="/terminal-assets/xterm.css"><style nonce="${nonce}">
:root{color-scheme:dark;--bg:#101722;--bg-2:#0c121b;--raised:#16202e;--rule:#26324a;--rule-2:#34435e;--text:#f1ede4;--muted:#93a0b6;--faint:#5f6d85;--claude:#f2a33c;--codex:#38d1c2;--bad:#ff6b6b;--ok:#38d1c2;--display:"Avenir Next Condensed","Helvetica Neue","Arial Narrow",sans-serif-condensed,sans-serif;--body:"Avenir Next","Helvetica Neue",Helvetica,Arial,sans-serif;--mono:"SF Mono",Menlo,Consolas,"Liberation Mono",monospace}
*{box-sizing:border-box}html{scroll-behavior:smooth}@media(prefers-reduced-motion:reduce){html{scroll-behavior:auto}*{animation:none!important;transition:none!important}}
body{margin:0;background:var(--bg);color:var(--text);font:14px/1.5 var(--body)}button,select{font:inherit}a{color:inherit}code,pre{font-family:var(--mono)}h1,h2,h3{margin:0}:focus-visible{outline:2px solid var(--claude);outline-offset:2px}
.eyebrow,.field>span,.context-label,.board-role,th,.lane-help,.terminal-state,.details h2{font-family:var(--display);font-weight:600;font-size:11px;letter-spacing:.14em;text-transform:uppercase;color:var(--faint)}
.topbar{position:sticky;top:0;z-index:20;display:flex;align-items:center;gap:18px;height:48px;padding:0 24px;background:var(--bg-2);border-bottom:1px solid var(--rule);font-family:var(--mono);font-size:12px;font-variant-numeric:tabular-nums}.brand{display:flex;align-items:center;gap:10px;text-decoration:none;min-width:0}.brand h1{font:600 15px/1 var(--display);letter-spacing:.06em;text-transform:uppercase;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.brand .mark{flex:none;border-radius:6px}.chips{display:flex;align-items:center;gap:0;margin-left:auto;color:var(--muted)}.chip{padding:0 14px;border-left:1px solid var(--rule);white-space:nowrap;text-decoration:none}.chip:first-child{border:0}.chip--warn{color:var(--claude)}.chip--ok{color:var(--ok)}.chip--ok i{display:inline-block;width:6px;height:6px;border-radius:50%;background:currentColor;margin-right:6px;vertical-align:1px}.top-chip{padding:0 14px;border-left:1px solid var(--rule)}.top-chip--running{color:var(--claude);text-decoration:none}.refresh:hover{color:var(--text)}
.page{max-width:1180px;margin:0 auto;padding:28px 24px 64px;display:grid;gap:36px}
.relay{display:grid;gap:18px}.relay-head h1{font:600 34px/1.05 var(--display);letter-spacing:-.005em;text-wrap:balance}.relay-status{margin:6px 0 0;color:var(--muted)}.relay-status strong{color:var(--text)}
.board{display:grid;grid-template-columns:1fr 72px 1fr;align-items:stretch;border-top:1px solid var(--rule);border-bottom:1px solid var(--rule)}.board-col{display:grid;gap:10px;padding:18px 0;align-content:start}.board-col--codex{padding-left:0}.board-head{display:flex;align-items:baseline;gap:10px}.board-swatch{width:10px;height:10px;border-radius:50%;background:var(--faint);align-self:center}.board-col--claude .board-swatch{background:var(--claude)}.board-col--codex .board-swatch{background:var(--codex)}.board-name{font:600 22px/1 var(--display);letter-spacing:.02em}.board-role{margin-left:auto}.is-next .board-role{color:var(--text)}.board-line{margin:0;color:var(--muted);font-family:var(--mono);font-size:12px;font-variant-numeric:tabular-nums}.board-line em.live{font-style:normal;color:var(--claude)}.board-col--codex .board-line em.live{color:var(--codex)}
.baton{position:relative;display:grid;place-items:center;color:var(--faint)}.baton-line{position:absolute;left:8px;right:8px;top:50%;height:1px;background:var(--rule-2)}.baton-arrow{position:relative;padding:0 8px;background:var(--bg);font:600 22px/1 var(--display)}.baton--to-codex .baton-arrow{color:var(--codex)}.baton--to-claude .baton-arrow{color:var(--claude)}
.relay-foot{display:flex;gap:24px;align-items:end;flex-wrap:wrap}.relay-hint{margin:0;color:var(--faint);font-size:12px;max-width:640px}.relay-hint code{color:var(--muted)}.howto{margin:0;padding-left:20px;color:var(--muted);font-size:13px;display:grid;gap:4px;max-width:720px}.howto b{color:var(--text);font-weight:600}
.button{display:inline-flex;align-items:center;gap:8px;border:1px solid var(--rule-2);border-radius:6px;background:transparent;color:var(--text);padding:8px 14px;cursor:pointer;font-family:var(--display);font-weight:600;font-size:14px;letter-spacing:.04em;text-transform:uppercase;transition:background 120ms,border-color 120ms}.button:hover{background:var(--raised);border-color:var(--muted)}.button:disabled{opacity:.35;cursor:not-allowed}.button small{font-family:var(--body);font-weight:400;font-size:12px;text-transform:none;letter-spacing:0;opacity:.75}.button--agent{justify-self:start;padding:11px 18px;font-size:15px}.button--claude{border-color:var(--claude);color:var(--claude)}.button--codex{border-color:var(--codex);color:var(--codex)}.button--primary{color:#101722!important}.button--claude.button--primary{background:var(--claude)}.button--claude.button--primary:hover{background:#ffb959}.button--codex.button--primary{background:var(--codex)}.button--codex.button--primary:hover{background:#5fe0d3}.button--ghost{border-color:transparent;color:var(--muted)}.button--ghost:hover{color:var(--text)}.button--danger{border-color:transparent;color:var(--bad)}.button--danger:hover{border-color:var(--bad)}.button--costly{border-color:var(--claude);color:var(--claude)}.button--secondary{}
.field{display:grid;gap:5px}.field select{min-width:220px;height:36px;padding:0 30px 0 10px;border:1px solid var(--rule-2);border-radius:6px;background:var(--bg-2);color:var(--text);font:13px var(--body)}
.stage{border:1px solid var(--rule);border-radius:8px;background:var(--bg-2);overflow:hidden;scroll-margin-top:60px}.lane-tabs{display:flex;align-items:stretch;border-bottom:1px solid var(--rule)}.lane-tab{display:inline-flex;align-items:center;gap:10px;padding:12px 18px;border:0;border-right:1px solid var(--rule);border-bottom:2px solid transparent;background:transparent;color:var(--muted);cursor:pointer;font-family:var(--display);font-weight:600;font-size:13px;letter-spacing:.08em;text-transform:uppercase}.lane-tab.is-active{color:var(--text);border-bottom-color:var(--text)}.lane-tab--claude.is-active{border-bottom-color:var(--claude)}.lane-tab--codex.is-active{border-bottom-color:var(--codex)}.lane-swatch{width:8px;height:8px;border-radius:50%;background:var(--faint)}.lane-swatch--claude{background:var(--claude)}.lane-swatch--codex{background:var(--codex)}.lane-time{font:12px var(--mono);color:var(--faint);letter-spacing:0;font-variant-numeric:tabular-nums}.lane-help{margin-left:auto;padding:0 16px;align-self:center;letter-spacing:.06em}
.lane-bar{display:flex;align-items:center;gap:14px;padding:10px 16px;border-bottom:1px solid var(--rule);background:var(--bg)}.lane-status{flex:1;min-width:0;color:var(--muted);font:12px var(--mono);overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.lane-controls{display:flex;gap:4px}.lane-controls .button{padding:5px 10px;font-size:12px}
.terminal-state{display:inline-flex;align-items:center;gap:7px;padding:4px 9px;border:1px solid var(--rule);border-radius:4px;white-space:nowrap}.terminal-state i{width:6px;height:6px;border-radius:50%;background:currentColor}.terminal-state--running{color:var(--claude);border-color:var(--claude)}.terminal-state--running.terminal-state--codex{color:var(--codex);border-color:var(--codex)}.terminal-state--running i{animation:pulse 1.6s infinite}.terminal-state--success{color:var(--ok);border-color:var(--ok)}.terminal-state--error{color:var(--bad);border-color:var(--bad)}@keyframes pulse{50%{opacity:.3}}
.terminal-window{background:#0a0f17}.terminal-window [id^="terminal-screen-"]{height:min(62vh,640px);padding:12px 14px;overflow:hidden;white-space:normal}.terminal-window [id^="terminal-screen-"] .xterm{height:100%;font-variant-ligatures:none}.terminal-window [id^="terminal-screen-"] .xterm-viewport{overflow-y:auto!important}
.lane-meta{display:grid;grid-template-columns:1.4fr .8fr .8fr 2fr .6fr;border-top:1px solid var(--rule);background:var(--bg)}.lane-meta>div{min-width:0;padding:8px 16px;border-right:1px solid var(--rule)}.lane-meta>div:last-child{border:0}.context-label{display:block;font-size:10px}.lane-meta strong{display:block;margin-top:2px;color:var(--muted);font:12px var(--mono);font-variant-numeric:tabular-nums;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}
.lane-note{margin:0;padding:10px 16px;color:var(--muted);font-size:12px;border-top:1px solid var(--rule)}.lane-note:empty{display:none}[id^="terminal-next-"]:empty{display:none}.next-heading{display:flex;flex-wrap:wrap;align-items:center;gap:8px;padding:12px 16px;border-top:1px solid var(--rule);color:var(--muted);font-size:13px}.next-heading strong{color:var(--text)}.next-heading code{padding:2px 7px;border:1px solid var(--rule);border-radius:4px;color:var(--text);font-size:12px}
.lane-manual{border-top:1px solid var(--rule)}.lane-manual summary{padding:10px 16px;color:var(--faint);font-size:12px;cursor:pointer;list-style:none}.lane-manual summary::before{content:'+ ';color:var(--faint)}.lane-manual[open] summary::before{content:'− '}.lane-manual form{display:flex;flex-wrap:wrap;gap:12px;align-items:end;padding:6px 16px 14px}.lane-manual .field select{min-width:160px}.lane-tip{margin:0;padding:0 16px 14px;color:var(--faint);font-size:12px}.lane-tip code{color:var(--muted)}
.duo{display:grid;grid-template-columns:1.5fr 1fr;gap:36px}.card h2{display:flex;justify-content:space-between;align-items:baseline;padding-bottom:10px;border-bottom:1px solid var(--rule);font:600 18px/1 var(--display);letter-spacing:.03em}.card h2 small{font:12px var(--body);color:var(--faint)}
.journal{margin:14px 0 0;max-height:300px;overflow:auto;padding:4px 0 4px 18px;border-left:2px solid var(--claude);color:var(--text);font:12.5px/1.7 var(--mono);white-space:pre-wrap;overflow-wrap:anywhere}.recent{list-style:none;margin:10px 0 0;padding:0}.recent li{display:flex;align-items:center;gap:12px;padding:9px 0;border-bottom:1px solid var(--rule);font:12px var(--mono);font-variant-numeric:tabular-nums}.recent-text{flex:1;min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;color:var(--muted)}.recent-text strong{color:var(--text);font-weight:500}.recent-when{color:var(--faint);white-space:nowrap}
.details h2{margin:0 0 6px;padding-bottom:10px;border-bottom:1px solid var(--rule)}.drawer{border-bottom:1px solid var(--rule)}.drawer summary{display:flex;align-items:center;gap:14px;padding:13px 4px;cursor:pointer;list-style:none;font:600 15px/1 var(--display);letter-spacing:.04em}.drawer summary::-webkit-details-marker{display:none}.drawer summary::before{content:'›';width:12px;color:var(--faint);transition:transform 120ms}.drawer[open] summary::before{transform:rotate(90deg)}.drawer summary>span{flex:1}.drawer summary small{font:12px var(--mono);color:var(--faint);font-variant-numeric:tabular-nums}.drawer-body{padding:4px 4px 20px 30px}
.badge{display:inline-flex;align-items:center;gap:6px;padding:2px 8px;border:1px solid var(--rule-2);border-radius:4px;color:var(--muted);font:11px var(--mono);white-space:nowrap}.badge i{width:5px;height:5px;border-radius:50%;background:currentColor}.badge--positive{color:var(--ok);border-color:rgba(56,209,194,.4)}.badge--negative{color:var(--bad);border-color:rgba(255,107,107,.4)}.badge--active{color:var(--claude);border-color:rgba(242,163,60,.4)}.badge--claude{color:var(--claude);border-color:rgba(242,163,60,.4)}.badge--codex{color:var(--codex);border-color:rgba(56,209,194,.4)}
.table-wrap{overflow:auto}table{width:100%;border-collapse:collapse;font-size:13px}th{padding:8px 12px 8px 0;text-align:left;border-bottom:1px solid var(--rule-2);white-space:nowrap}td{max-width:360px;padding:10px 12px 10px 0;border-bottom:1px solid var(--rule);vertical-align:top;overflow-wrap:anywhere;color:var(--muted)}td strong{color:var(--text);font-weight:500}td small,time{display:block;color:var(--faint);font:11px var(--mono);margin-top:2px}.artifact-list{display:flex;flex-wrap:wrap;gap:6px}.artifact-link{padding:1px 7px;border:1px solid var(--rule-2);border-radius:4px;font:11px var(--mono);text-decoration:none;color:var(--muted)}.artifact-link:hover{color:var(--text)}.arrow{padding:0 6px;color:var(--faint)}.task-id{color:var(--faint);font:11px var(--mono)}.file-pill{display:block;color:var(--muted);font:11px var(--mono)}
.action-form{display:inline-block;margin:2px 4px 2px 0}.action-cluster{display:flex;flex-wrap:wrap;margin-top:8px}.action-cluster .button{padding:5px 10px;font-size:12px}.command{display:flex;align-items:center;gap:12px;margin:6px 0;padding:8px 8px 8px 0;border-bottom:1px solid var(--rule)}.command code{flex:1;color:var(--muted);font-size:12px;overflow-wrap:anywhere;white-space:pre-wrap}.copy-button{display:inline-flex;align-items:center;gap:6px;padding:4px 9px;border:1px solid var(--rule-2);border-radius:4px;background:transparent;color:var(--muted);font:12px var(--body);cursor:pointer}.copy-button:hover{color:var(--text);border-color:var(--muted)}
.note{margin:12px 0 0;color:var(--faint);font-size:12px}.empty{padding:14px 0;color:var(--faint);font-size:13px}.empty strong{display:block;color:var(--muted);font-weight:500}.output{max-height:360px;overflow:auto;margin:10px 0 0;padding:12px 14px;border:1px solid var(--rule);border-radius:6px;background:var(--bg-2);color:var(--text);white-space:pre-wrap;overflow-wrap:anywhere;font-size:12px}.action-result{margin-top:14px;padding-top:12px;border-top:1px solid var(--rule)}.action-result h3{display:flex;gap:10px;align-items:center;font:500 14px var(--body)}.action-result--failure h3{color:var(--bad)}.warnings{padding:12px 14px;border:1px solid var(--bad);border-radius:6px;color:var(--bad);font-size:13px}footer{color:var(--faint);font:11px var(--mono)}details summary{cursor:pointer}
@media(max-width:900px){.duo{grid-template-columns:1fr}.board{grid-template-columns:1fr;border:0}.board-col{border-top:1px solid var(--rule)}.baton{display:none}.lane-meta{grid-template-columns:1fr 1fr}.chips .chip--git{display:none}}@media(max-width:600px){.topbar{padding:0 16px}.page{padding:20px 16px 40px;gap:28px}.relay-head h1{font-size:28px}.lane-help{display:none}.lane-bar{flex-wrap:wrap}.terminal-window [id^="terminal-screen-"]{height:50vh}.field select{min-width:0;width:100%}.button--agent{width:100%;justify-content:center}}
</style></head><body>
<header class="topbar"><a class="brand" href="#work">${logoSvg(24)}<h1>${esc(s.config.projectName)}</h1></a><div class="chips"><span class="chip chip--git">${esc(s.git.branch)}</span><span class="chip chip--git${s.git.repository&&s.git.changes.length?' chip--warn':''}">${esc(gitLabel)}</span>${latest?.status==='running'?`<a class="top-chip top-chip--running" href="#dashboard-actions">running ${esc(latest.command)}</a>`:''}<span class="chip chip--ok"><i></i>Local-only</span><a class="chip refresh" href="/">refresh</a></div></header>
<main class="page">
${relayBar(s,token)}
${terminalPanel(s.tasks,token)}
<div class="duo"><section class="card" id="journal"><h2>Shared journal <small>what the agents tell each other</small></h2>${journal?`<pre class="journal">${esc(journal)}</pre>`:empty('Empty so far','Agents append entries here as they work, ending with a handoff entry.')}</section>
<section class="card" id="activity"><h2>Recent sessions <small>${s.sessions.length} recorded</small></h2>${recent?`<ul class="recent">${recent}</ul>`:empty('No sessions yet','Sessions appear here after the first launch.')}</section></div>
<section class="details" id="details"><h2>Project details</h2>
${drawer('dashboard-actions','Quick actions',latest?`${latest.status}: ${latest.command}`:'sync, resume brief',`<div class="action-cluster">${form('sync','Sync project')}${form('resume','Generate resume brief')}</div>${latest?`<div class="action-result action-result--${latest.status}" data-summary="${esc(latest.status)}: ${esc(latest.command)}"><h3>${badge(latest.status)} ${esc(latest.command)}</h3><p class="note">Logs: ${esc(latest.folder)}</p><pre class="output">${esc(latest.output||'Running… this page refreshes every 3 seconds until the action finishes.')}</pre></div>`:''}`,latest?.status==='running')}
${drawer('actions','Recommended commands',`${Math.min(actions.length,12)} suggested`,actions.slice(0,12).join('')||empty('You are caught up','No next action is currently suggested.'))}
${drawer('agents','Agents',s.available.map(a=>`${display(a.agent)} ${a.availability}`).join(' · ')||'none',table(['Agent','CLI','Model','Effort / permission','Usage'],s.available.map(a=>[agentBadge(a.agent),`${badge(a.availability)}<small>${esc(a.executable||'Not found')}</small>`,esc(a.config.model||'Native default'),esc([a.config.effort,a.config.permissionMode].filter(Boolean).join(' / ')||'Native default'),`<strong>Unknown</strong>`]),'No agents configured')+'<p class="note">Usage is unknown here. Run native <code>/status</code> inside a session for authoritative account usage.</p>')}
${drawer('tasks','Tasks',`${s.tasks.filter(t=>t.status!=='done').length} open`,table(['Task','Status','Agent','Files','Actions'],s.tasks.map(t=>[`<span class="task-id">${esc(t.id)}</span><br><strong>${esc(t.title)}</strong>`,badge(t.status),t.assignedAgent?agentBadge(t.assignedAgent):'Unassigned',t.files.map(f=>`<span class="file-pill">${esc(f)}</span>`).join('')||'—',`<details><summary>Copyable commands</summary>${t.assignedAgent?copy(cmd('run',t.id,'--agent',t.assignedAgent,'--worktree','auto','--review'))+copy(cmd('attach',t.assignedAgent,'--task',t.id,'--worktree','existing')):'Assign an agent before running.'}${copy(cmd('complete',t.id))}</details>${taskActions(t.id,t.assignedAgent)}`]),'No tasks yet'))}
${drawer('worktrees','Worktrees',`${s.trees.length} registered`,table(['Agent / branch','Path','State','Actions'],s.trees.map(w=>[`${agentBadge(w.agent)}<small>${esc(w.branch)}</small>`,`<code>${esc(w.path)}</code>`,'error'in w?badge('error')+`<small>${esc(w.error)}</small>`:badge(!w.git?.repository?'unavailable':w.git.changes.length?'dirty':'clean'),`<div class="action-cluster">${form('review',`Review ${w.agent} + Save`,{agent:w.agent})}</div>${copy(cmd('review',w.agent,'--save'))}${copy(cmd('attach',w.agent,'--worktree','existing'))}`]),'No worktrees registered')+'<p class="note">Worktrees are for parallel work. The relay flow above uses the project directory directly.</p>')}
${drawer('sessions','All sessions',`${s.sessions.length} recent`,table(['Agent','Task','Mode','Outcome','Started / ended','Artifacts'],sessionRows,'No sessions yet'))}
${drawer('switches','Patch transfers',`${s.switches.length} recent`,table(['Task','Transfer','Applied','Continued','Saved / artifacts','Next command'],switchRows,'No switches yet'))}
${drawer('reviews','Saved reviews',`${s.reviews.length} recent`,table(['Agent','Task','Created / saved','Path / artifact'],s.reviews.map(r=>[agentBadge(r.data.agent),esc(value(r.data.taskId)),`<time>${esc(r.time)}</time>`,`<code>${esc(value(r.data.path))}</code><div class="artifact-list">${links(r)}</div>`]),'No saved reviews yet'))}
</section>
${s.warnings.length?`<div class="warnings">${s.warnings.map(esc).join('<br>')}</div>`:''}<footer>Snapshot ${esc(new Date().toISOString())} · everything on this page is local · artifacts open as plain text</footer></main>
<script nonce="${nonce}">document.querySelectorAll('[data-copy]').forEach(button=>button.addEventListener('click',async()=>{try{await navigator.clipboard.writeText(button.dataset.copy);button.innerHTML='<span aria-hidden="true">✓</span> Copied';setTimeout(()=>button.innerHTML='<span aria-hidden="true">⧉</span> Copy',1500);}catch{const selection=window.getSelection();const range=document.createRange();range.selectNodeContents(button.previousElementSibling);selection.removeAllRanges();selection.addRange(range);button.textContent='Select & copy';}}));</script><script nonce="${nonce}" src="/terminal-assets/xterm.js"></script><script nonce="${nonce}" src="/terminal-assets/fit.js"></script><script nonce="${nonce}" src="/terminal-assets/client.js"></script></body></html>`;
}
