import {escapeHtml as esc} from './dashboard-actions.js';
import type {Task} from '../types/index.js';
import type {DashboardState} from './dashboard-state.js';
import {display} from './work.js';

// Brand mark: two chevrons passing a baton, amber (Claude Code) and teal (Codex).
export const logoSvg=(size=28)=>`<svg class="mark" width="${size}" height="${size}" viewBox="0 0 64 64" aria-hidden="true"><rect width="64" height="64" rx="16" fill="#141a26"/><path d="M14 18l14 14-14 14" fill="none" stroke="#f5a54a" stroke-width="7" stroke-linecap="round" stroke-linejoin="round"/><path d="M50 18L36 32l14 14" fill="none" stroke="#3dd6c4" stroke-width="7" stroke-linecap="round" stroke-linejoin="round"/><circle cx="32" cy="32" r="4.5" fill="#e8ecf4"/></svg>`;

const when=(v:string|null|undefined)=>{if(!v)return '';const ms=Date.now()-Date.parse(v);if(!Number.isFinite(ms))return v;const m=Math.round(ms/60000);if(m<1)return 'just now';if(m<60)return `${m} min ago`;const h=Math.round(m/60);if(h<48)return `${h} h ago`;return `${Math.round(h/24)} d ago`;};

// The relay bar: who ran last, who is next, one primary action. Section id "work" is the page's anchor.
export function relayBar(s:DashboardState,token:string){
    const last=s.work.last;const next=s.work.next;const prev=next==='claude'?'codex':'claude';
    const button=(agent:string)=>token?`<button class="button button--agent button--${agent} ${agent===next?'button--primary':''} work-launch" type="button" data-work-agent="${agent}">▶ Continue with ${esc(display(agent))}${agent===next?' <small>(recommended)</small>':''}</button>`:'';
    const column=(agent:string)=>{const mine=last?.agent===agent?last:undefined;const role=agent===next?'up next':mine?'worked last':'standing by';
        const line=mine?(mine.endedAt?`ended ${esc(when(mine.endedAt))}${mine.taskId?` · ${esc(mine.taskId)}`:''}`:`<em class="live">running</em> since ${esc(when(mine.startedAt))}`):agent===next&&last?`will receive the baton`:'no session yet';
        return `<div class="board-col board-col--${agent}${agent===next?' is-next':''}"><div class="board-head"><span class="board-swatch"></span><span class="board-name">${esc(display(agent))}</span><span class="board-role">${role}</span></div><p class="board-line">${line}</p>${button(agent)}</div>`;};
    const tasks=`<label class="field"><span>Task</span><select id="work-task"><option value="">No task</option>${s.tasks.filter(t=>t.status!=='done').map(t=>`<option value="${esc(t.id)}"${last?.taskId===t.id?' selected':''}>${esc(t.id)} — ${esc(t.title)}</option>`).join('')}</select></label>`;
    const status=last?`<strong>${esc(display(last.agent))}</strong> worked last${last.taskId?` on ${esc(last.taskId)}`:''}`:'';
    const howto=last?'':`<ol class="howto"><li>Pick an agent. It opens normally in the lane below.</li><li>A single line is placed in its input box pointing at the shared context. Press Enter when you are ready.</li><li>When that agent runs out of usage, just continue with the other one. It receives the session log, the journal and the diff automatically. <b>Hand off</b> is optional, for when the agent still has budget to summarize.</li></ol>`;
    return `<section id="work" class="relay"><div class="relay-head"><h1>${last?`Hand the baton to ${esc(display(next))}`:'Start the first session'}</h1><p class="relay-status">${status||'Either agent can start. The other one picks up from the shared journal later.'}</p></div>
<div class="board">${column('claude')}<div class="baton baton--to-${next}" aria-hidden="true"><span class="baton-line"></span><span class="baton-arrow">${next==='codex'?'→':'←'}</span></div>${column('codex')}</div>
<div class="relay-foot">${tasks}<p class="relay-hint">Handed over automatically: the previous agent's own session log, the shared journal, current <code>git status</code>, and everything changed since it started. Nothing is asked of the agent that ran out. Terminal equivalent: <code>agenthub work</code></p></div>${howto}</section>`;
}

export function terminalPanel(tasks:Task[],token:string){
    return `<section id="embedded-terminal" class="stage"><div class="lane-tabs" role="tablist">${['left','right'].map((pane,i)=>`<button class="lane-tab${i===0?' is-active':''}" role="tab" type="button" data-lane-tab="${pane}" aria-selected="${i===0}"><span class="lane-swatch"></span><span class="lane-label">Lane ${i+1} · empty</span><span class="lane-time"></span></button>`).join('')}<span class="lane-help">Continue picks a free lane. Both can run at once.</span></div>${['left','right'].map((pane,i)=>lane(tasks,token,pane,i===0)).join('')}</section>`;
}

function lane(tasks:Task[],token:string,pane:string,visible:boolean){return (`<div class="lane" data-terminal-pane="${pane}"${visible?'':' hidden'}>
<div class="lane-bar"><span id="terminal-state" class="terminal-state terminal-state--idle"><i></i>Idle</span><span id="terminal-status" class="lane-status" role="status">Empty lane. Use Continue above, or open manual launch.</span><div class="lane-controls"><button class="button button--ghost" id="terminal-handoff-request" type="button" disabled title="Optional: if the agent still has budget, ask it to write a handoff entry. Not required: its session log and diff are handed over automatically.">✎ Hand off</button><button class="button button--ghost" id="terminal-reconnect" type="button">↻ Reconnect</button><button class="button button--danger" id="terminal-stop" type="button" disabled>■ Stop</button></div></div>
<div class="terminal-window"><div id="terminal-screen"></div></div>
<div class="lane-meta"><div><span class="context-label">Session</span><strong id="terminal-session">Not started</strong></div><div><span class="context-label">Agent</span><strong id="terminal-agent">—</strong></div><div><span class="context-label">Task</span><strong id="terminal-task">—</strong></div><div><span class="context-label">Directory</span><strong id="terminal-worktree">—</strong></div><div><span class="context-label">Elapsed</span><strong id="terminal-elapsed">00:00</strong></div></div>
<p id="terminal-handoff" class="lane-note"></p><div id="terminal-next"></div>
<details class="lane-manual"><summary>Manual launch</summary><form id="terminal-launch"><input type="hidden" name="token" value="${esc(token)}"><label class="field"><span>Agent</span><select name="agent"><option value="codex">Codex</option><option value="claude">Claude Code</option></select></label><label class="field"><span>Task</span><select name="task"><option value="">No task</option>${tasks.map(t=>`<option value="${esc(t.id)}">${esc(t.id)} — ${esc(t.title)}</option>`).join('')}</select></label><label class="field"><span>Worktree</span><select name="worktree"><option>none</option><option>existing</option><option>auto</option></select></label><label class="field"><span>Context</span><select name="prompt"><option value="ready">Context ready, you press Enter</option><option value="auto">Auto-continue</option><option value="none">No prompt</option></select></label><button class="button button--primary terminal-launch" type="submit">▶ Launch</button></form><p class="lane-tip">Native <code>/status</code>, <code>/model</code> and <code>/compact</code> work as usual. Keep browser zoom at 100% for best rendering.</p></details>
</div>`).replace(/id="(terminal-[^"]+)"/g,`id="$1-${pane}"`).replace('value="claude"','value="claude"'+(pane==='left'?' selected':''));}

export const terminalClient=String.raw`const AGENT_NAME={claude:'Claude Code',codex:'Codex'};
const laneTab=pane=>document.querySelector('[data-lane-tab="'+pane+'"]');
function activateLane(pane){document.querySelectorAll('[data-lane-tab]').forEach(t=>{const on=t.dataset.laneTab===pane;t.classList.toggle('is-active',on);t.setAttribute('aria-selected',String(on));});document.querySelectorAll('[data-terminal-pane]').forEach(l=>{l.hidden=l.dataset.terminalPane!==pane;});window.dispatchEvent(new Event('resize'));}
document.querySelectorAll('[data-lane-tab]').forEach(t=>t.addEventListener('click',()=>activateLane(t.dataset.laneTab)));
document.querySelectorAll('[data-terminal-pane]').forEach(root=>{
const pane=root.dataset.terminalPane;
const el=id=>document.getElementById(id+'-'+pane);
const launch=el('terminal-launch');if(!launch)return;
const token=launch.elements.token.value,status=el('terminal-status'),stop=el('terminal-stop'),state=el('terminal-state'),handoffButton=el('terminal-handoff-request');
const sessionLabel=el('terminal-session'),agentLabel=el('terminal-agent'),taskLabel=el('terminal-task'),worktreeLabel=el('terminal-worktree'),elapsedLabel=el('terminal-elapsed');
const tab=laneTab(pane),tabLabel=tab.querySelector('.lane-label'),tabTime=tab.querySelector('.lane-time'),tabSwatch=tab.querySelector('.lane-swatch');
let term,fit,session=null,controller,queue=Promise.resolve(),stopping=false,timer,resizeTimer;
const tell=e=>{status.textContent=e.message||String(e);state.className='terminal-state terminal-state--error';state.innerHTML='<i></i>Error';};
const duration=ms=>{const seconds=Math.max(0,Math.floor(ms/1000));return String(Math.floor(seconds/60)).padStart(2,'0')+':'+String(seconds%60).padStart(2,'0');};
const tick=()=>{if(!session){elapsedLabel.textContent='00:00';tabTime.textContent='';return;}const end=session.endedAt?Date.parse(session.endedAt):Date.now();const text=duration(end-Date.parse(session.startedAt));elapsedLabel.textContent=text;tabTime.textContent=session.endedAt?'':text;};
async function post(endpoint,fields={}){const response=await fetch('/terminal/'+endpoint,{method:'POST',body:new URLSearchParams({token,pane,...fields})});if(!response.ok)throw new Error(await response.text());return response;}
try{term=new Terminal({cursorBlink:true,cursorStyle:'bar',scrollback:5000,fontSize:13,lineHeight:1,letterSpacing:0,fontFamily:'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, Liberation Mono, monospace',theme:{background:'#0a0d14',foreground:'#dde3ee',cursor:'#f5a54a',selectionBackground:'#2a3446',black:'#101420',red:'#ff7b86',green:'#3dd6c4',yellow:'#f5a54a',blue:'#6fb0ff',magenta:'#c39cff',cyan:'#5ee3ea',white:'#dde3ee'}});fit=new FitAddon.FitAddon();term.loadAddon(fit);term.open(el('terminal-screen'));fit.fit();term.writeln('\x1b[38;5;245mLane ready. Press Continue above to start an agent here.\x1b[0m');}catch(e){tell(new Error('Terminal UI unavailable. Use agenthub work in your terminal. '+e.message));return;}
function size(){return {cols:String(Math.max(2,term.cols||80)),rows:String(Math.max(2,term.rows||24))};}
function resize(){if(root.hidden)return;fit.fit();if(session&&!session.endedAt)post('resize',{session:session.sessionId,...size()}).catch(tell);}
new ResizeObserver(()=>{clearTimeout(resizeTimer);resizeTimer=setTimeout(resize,50);}).observe(el('terminal-screen'));
window.addEventListener('resize',()=>{clearTimeout(resizeTimer);resizeTimer=setTimeout(resize,50);});
term.onData(data=>{if(!session||session.endedAt||stopping)return;const id=session.sessionId;for(let i=0;i<data.length;i+=2048){const chunk=data.slice(i,i+2048);queue=queue.then(()=>post('input',{session:id,data:chunk})).catch(tell);}});
function recommendations(record){const target=el('terminal-next');target.replaceChildren();if(!record?.endedAt)return;const other=record.agent==='codex'?'claude':'codex';const heading=document.createElement('div');heading.className='next-heading';heading.innerHTML='<strong>Session over.</strong><span> Press Continue with '+AGENT_NAME[other]+' above to hand off, or review first:</span>';const code=document.createElement('code');code.textContent='agenthub review '+record.agent+' --save';heading.append(code);target.append(heading);}
function paint(record){const agent=record?.agent;tab.className='lane-tab'+(tab.classList.contains('is-active')?' is-active':'')+(agent&&!record.endedAt?' lane-tab--'+agent:'');tabSwatch.className='lane-swatch'+(agent?' lane-swatch--'+agent:'');tabLabel.textContent=!record?'Lane '+(pane==='left'?1:2)+' · empty':AGENT_NAME[agent]+(record.endedAt?' · ended':'');}
function show(record){if(record&&record.sessionId!==session?.sessionId)term.reset();session=record;clearInterval(timer);stop.disabled=!record||!!record.endedAt;handoffButton.disabled=!record||!!record.endedAt;launch.querySelector('button').disabled=!!record&&!record.endedAt;sessionLabel.textContent=record?.sessionId||'Not started';agentLabel.textContent=record?AGENT_NAME[record.agent]||record.agent:'—';taskLabel.textContent=record?.taskId||'No task';worktreeLabel.textContent=record?.workdir||'—';tick();if(record&&!record.endedAt)timer=setInterval(tick,1000);recommendations(record);paint(record);if(!record){state.className='terminal-state terminal-state--idle';state.innerHTML='<i></i>Idle';status.textContent='Empty lane. Use Continue above, or open manual launch.';return;}if(record.endedAt){state.className='terminal-state '+(record.exitCode===0?'terminal-state--success':'terminal-state--error');state.innerHTML='<i></i>'+(record.signal?'Stopped':'Exited');status.textContent=(record.signal?'Stopped (signal '+record.signal+')':'Exited with code '+record.exitCode)+(record.error?' — '+record.error:'')+' · logs in '+record.folder;}else{state.className='terminal-state terminal-state--running terminal-state--'+record.agent;state.innerHTML='<i></i>Running';status.textContent=AGENT_NAME[record.agent]+' in '+record.workdir;}
el('terminal-handoff').textContent=record.promptMode==='ready'&&record.promptPath?'Context is typed into the input box once the agent is ready. Review it and press Enter to start. Full context: '+record.promptPath:record.promptPath?'Continuation prompt submitted automatically. Saved copy: '+record.promptPath:record.handoffPath?'Handoff saved: '+record.handoffPath+'. Open it locally and paste into the CLI when ready. No prompt was submitted automatically.':'';}
async function connect(){if(controller)controller.abort();controller=new AbortController();term.reset();try{const r=await fetch('/terminal/events',{method:'POST',body:new URLSearchParams({token,pane}),signal:controller.signal});if(!r.ok)throw new Error(await r.text());const reader=r.body.getReader(),decoder=new TextDecoder();let pending='';while(true){const {done,value}=await reader.read();if(done)break;pending+=decoder.decode(value,{stream:true});let end;while((end=pending.indexOf('\n\n'))>=0){const frame=pending.slice(0,end);pending=pending.slice(end+2);if(frame.startsWith('data: ')){const event=JSON.parse(frame.slice(6));if(event.type==='output')term.write(event.data);else if(event.type==='status')show(event.record);}}}status.textContent+=' · Display disconnected. Reconnect to restore recent output.';}catch(e){if(e.name!=='AbortError')tell(e);}}
launch.addEventListener('submit',async e=>{e.preventDefault();activateLane(pane);fit.fit();const values=Object.fromEntries(new FormData(launch));const command='agenthub '+(values.prompt==='none'?'attach '+values.agent:'work '+values.agent+(values.prompt==='auto'?' --auto':''))+(values.task?' --task '+values.task:'')+' --worktree '+values.worktree;if(!confirm('Start '+AGENT_NAME[values.agent]+' in this lane?\n'+command+'\nThis uses your native CLI and subscription and may modify files. '+(values.prompt==='auto'?'The shared continuation prompt is submitted automatically.':values.prompt==='ready'?'A one-line instruction is typed into the input box; nothing runs until you press Enter.':'No prompt is auto-submitted.')))return;launch.querySelector('button').disabled=true;state.className='terminal-state terminal-state--running';state.innerHTML='<i></i>Starting';try{session=await(await post('launch',{...values,confirmed:'yes',...size()})).json();show(session);term.focus();}catch(e){tell(e);launch.querySelector('button').disabled=false;}});
stop.addEventListener('click',async()=>{if(!session)return;stopping=true;stop.disabled=true;state.innerHTML='<i></i>Stopping';try{await post('stop',{session:session.sessionId});}catch(e){tell(e);}finally{stopping=false;}});
handoffButton.addEventListener('click',async()=>{if(!session||session.endedAt)return;if(!confirm('Ask '+AGENT_NAME[session.agent]+' to write its handoff entry now? This types a request into the running session.'))return;try{await post('input',{session:session.sessionId,data:'Please append your handoff entry to .agenthub/memory/journal.md now: current state, uncommitted files, exact next steps, open questions. Then stop.\r'});status.textContent='Handoff requested. When it is written, press Continue with the other agent.';term.focus();}catch(e){tell(e);}});
el('terminal-reconnect').addEventListener('click',connect);connect();
});
document.querySelectorAll('[data-work-agent]').forEach(button=>button.addEventListener('click',()=>{
const free=['left','right'].map(p=>document.getElementById('terminal-launch-'+p)).find(f=>f&&!f.querySelector('button').disabled);
if(!free){alert('Both lanes are busy. Stop one first.');return;}
const pane=free.closest('[data-terminal-pane]').dataset.terminalPane;
free.elements.agent.value=button.dataset.workAgent;free.elements.task.value=document.getElementById('work-task').value;free.elements.worktree.value='none';free.elements.prompt.value='ready';
activateLane(pane);document.getElementById('embedded-terminal').scrollIntoView({behavior:'smooth',block:'start'});free.requestSubmit();
}));`;
